import { View } from '../src/View';
import {
  Scene,
} from '@zeainc/zea-engine'

describe('View', () => {
  it('Should create a valid view', () => {
    const scene = new Scene()
    let view = new View('View 1', scene)
    expect(view.name).toEqual('View 1');
    expect(view.pose).not.toBeNull();

    let require1 = require('./data/simpleView.json')

    let viewJson = view.saveJson()
    viewJson.id = '' // hack : ignore the autogenerated ID
    expect(viewJson).toEqual(require1);
  });
});
