name: GitHub Actions Demo

on: [push]

jobs:
  IPC-3D-E2E:
    runs-on: ubuntu-latest
    steps:
      - run: yarn run build

      - run: yarn run serve:ci

      - run: yarn run cypress run --record --key ${{ secrets.CYPRESS_KEY }}
